feat: added support for syncing only major versions.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,3 +52,41 @@ jobs:
         run: |
           echo "Invalid new version ${{ steps.sync-release-version.outputs.new_version }}: Expected 1.0.2"
           exit 1
+            - name: Sync release Version
+      - name: Sync release Version Major
+        uses: ./
+        id: sync-release-version-major
+        with:
+          current_version: '1.0.1'
+          new_version: '2.0.0'
+          only_major: true
+          paths: |
+            test/README.md
+            test/subdir/README.md
+      - name: Verify Changed files
+        uses: tj-actions/verify-changed-files@v11
+        id: changed_files_major
+        with:
+          files: |
+            test/README.md
+            test/subdir/README.md
+      - name: Validate files changed.
+        if: steps.changed_files_major.outputs.files_changed != 'true'
+        run: |
+          echo "Expected versions changes."
+          echo "Found: \n"
+          cat test/README.md
+          echo "------"
+          cat test/subdir/README.md
+          exit 1
+      - name: Validate old_version output.
+        if: steps.sync-release-version-major.outputs.old_version != '1'
+        run: |
+          echo "Invalid previous version ${{ steps.sync-release-version-major.outputs.old_version }}: Expected 1.0.1"
+          exit 1
+      - name: Validate new_version output.
+        if: steps.sync-release-version-major.outputs.new_version != '2'
+        run: |
+          echo "Invalid new version ${{ steps.sync-release-version-major.outputs.new_version }}: Expected 1.0.2"
+          exit 1
+      
